import Head from "next/head";
import Image from "next/image";
import Main from "../components/Main";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Revolut – One app, all things money</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
    </>
  );
}
